baseURL = 'https://688c2a9d3a18488a944b0840--kaleidoscopic-croquembouche-225c8f.netlify.app/'
languageCode = 'en-us'
title = 'black offset'
theme = 'hugo-PaperMod-master'
enableRobotsTXT = false

[params]
  ShowReadingTime = true
  env = "production"
