backend:
  name: github
  repo: agustedone/security-blog
  branch: main
  auth_type: implicit
media_folder: "static/uploads"
public_folder: "/uploads"
collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Fecha", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }

